"""initial_schema

Revision ID: 8fe1363d3a48
Revises: 
Create Date: 2026-09-01 22:23:13.845753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe1363d3a48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_code', sa.String(length=50), nullable=False),
    sa.Column('team_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_team_code'), 'teams', ['team_code'], unique=True)
    op.create_table('users',
    sa.Column('user_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_expiry_days', sa.Integer(), nullable=False),
    sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_team_active', 'users', ['team_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_team_id'), 'audit_logs', ['team_id'], unique=False)
    op.create_index('ix_audit_logs_team_time', 'audit_logs', ['team_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_user_time', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('categories',
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allow_stage_skipping', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_category_code'), 'categories', ['category_code'], unique=True)
    op.create_index('ix_categories_team_active', 'categories', ['team_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_categories_team_id'), 'categories', ['team_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('category_stages',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(length=200), nullable=False),
    sa.Column('stage_description', sa.Text(), nullable=True),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_completion_stage', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_stages_category_id'), 'category_stages', ['category_id'], unique=False)
    op.create_index('ix_category_stages_order', 'category_stages', ['category_id', 'stage_order'], unique=False)
    op.create_table('tasks',
    sa.Column('task_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_assigned_status', 'tasks', ['assigned_to', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_category_id'), 'tasks', ['category_id'], unique=False)
    op.create_index('ix_tasks_category_status', 'tasks', ['category_id', 'status'], unique=False)
    op.create_index('ix_tasks_created_by_created_at', 'tasks', ['created_by', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index('ix_tasks_due_date_status', 'tasks', ['due_date', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_number'), 'tasks', ['task_number'], unique=True)
    op.create_index('ix_tasks_team_created', 'tasks', ['team_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_team_id'), 'tasks', ['team_id'], unique=False)
    op.create_index('ix_tasks_team_status', 'tasks', ['team_id', 'status'], unique=False)
    op.create_table('task_delegations',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('delegated_by', sa.UUID(), nullable=False),
    sa.Column('previous_assignee', sa.UUID(), nullable=True),
    sa.Column('delegated_to', sa.UUID(), nullable=False),
    sa.Column('delegated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['delegated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delegated_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_assignee'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_delegations_task_id'), 'task_delegations', ['task_id'], unique=False)
    op.create_table('task_stages',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('original_category_stage_id', sa.UUID(), nullable=True),
    sa.Column('stage_name', sa.String(length=200), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_completion_stage', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_category_stage_id'], ['category_stages.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_stages_task_id'), 'task_stages', ['task_id'], unique=False)
    op.create_index('ix_task_stages_task_order', 'task_stages', ['task_id', 'stage_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_stages_task_order', table_name='task_stages')
    op.drop_index(op.f('ix_task_stages_task_id'), table_name='task_stages')
    op.drop_table('task_stages')
    op.drop_index(op.f('ix_task_delegations_task_id'), table_name='task_delegations')
    op.drop_table('task_delegations')
    op.drop_index('ix_tasks_team_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_team_id'), table_name='tasks')
    op.drop_index('ix_tasks_team_created', table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_number'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index('ix_tasks_due_date_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index('ix_tasks_created_by_created_at', table_name='tasks')
    op.drop_index('ix_tasks_category_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_category_id'), table_name='tasks')
    op.drop_index('ix_tasks_assigned_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_category_stages_order', table_name='category_stages')
    op.drop_index(op.f('ix_category_stages_category_id'), table_name='category_stages')
    op.drop_table('category_stages')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_categories_team_id'), table_name='categories')
    op.drop_index('ix_categories_team_active', table_name='categories')
    op.drop_index(op.f('ix_categories_category_code'), table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_audit_logs_user_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_team_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_team_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index('ix_users_team_active', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_team_code'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
